android: Skip scsi-disk + scsi-generic (Linux SG_IO assumptions)
Both files include <scsi/sg.h> and reference SG_ERR_DRIVER_TIMEOUT and
related ioctl constants that Bionic's scsi/sg.h doesn't define:

  hw/scsi/scsi-disk.c:2843:44: error: use of undeclared identifier
    'SG_ERR_DRIVER_TIMEOUT'

  hw/scsi/scsi-generic.c also fails with macro-redefinition warnings
    promoted to errors under -Werror (CHECK_CONDITION / RESERVATION_
    CONFLICT clashing with Bionic's scsi/sg.h definitions).

Xbox emulation has no SCSI bus - it uses IDE - so we don't need
either file in libxemu.so. Gate the two unconditionally-added sources
on host_os != 'android'.